-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "price" SET DATA TYPE INTEGER,
ALTER COLUMN "costPrice" SET DATA TYPE INTEGER;

-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "total" SET DATA TYPE INTEGER,
ALTER COLUMN "cashReceived" SET DATA TYPE INTEGER,
ALTER COLUMN "due" SET DATA TYPE INTEGER;

-- AlterTable
ALTER TABLE "OrderProducts" ALTER COLUMN "price" SET DATA TYPE INTEGER;

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "cashReceived" SET DATA TYPE INTEGER;